services:

  db:
    image: postgres:18
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@watchtower.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  prestart:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: bash scripts/prestart.sh
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      prestart:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - PFSENSE_SSH_HOST=192.168.1.1
      - PFSENSE_SSH_USER=root
      - PFSENSE_SSH_KEY=/app/ssh/watchtower-ansible
        #- PIHOLE_URL=http://192.168.50.100
        #- PIHOLE_PASSWORD=your_pihole_web_password
        #- PFSENSE_URL=http://192.168.1.1
        #- PFSENSE_API_KEY=your_pfsense_api_key
        #- PFSENSE_INSTANCE=192.168.1.1:9100
    volumes:
      - ./secrets/ansible_id_ed25519:/app/secrets/ansible_id_ed25519:ro- 
      - ./ssh:/app/ssh


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - NODE_ENV=production
    restart: always
    ports:
      - "80:80"

  telegram-bot:
    build:
      context: ./telegram-bot
    restart: unless-stopped
    env_file:
      - ./telegram-bot/.env
    depends_on:
      - backend
    networks:
      - watchtower-dash_default

volumes:
  app-db-data:
  pgadmin-data:

networks:
  watchtower-dash_default:
    external: true



